tinyMCE.addI18n('en.wpdojoloader',{
	wpdojoloader: 'Wp Dojo Loader',
	dojowidgets: 'Dojo Widgets',
	tabcontainer : 'Tabcontainer',
	contentpane  : 'Contentpane',
	datagrid: 'Datagrid',
	accordioncontainer: 'Accordion Container',
	accordionpane: 'Accordion Pane',
	accordion: 'Accordion',
	fisheye: 'Fisheye',
	scrollpane: 'Scroll Pane',
	box: 'Box',
	bordercontainer: 'Border Container',
	dojocontent: 'Dojo Content Tags',
	links: 'Links',
	pagelink: 'Link to Page',
	postlink: 'Link to Post',
	catlink: 'Link to Category',
	hyperlink: 'Hyperlink',
	insert: 'Insert',
	insertpage: 'Page',
	insertpost: 'Post',
	calltemplate: 'Call Template',
	content: 'Content',
	import: 'Import',
});
